name: open_source_software
description: "open_source_software"
version: 1.0.1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  geolocator: ^14.0.2
  maps_toolkit: ^3.1.0
  dart_geohash: ^2.1.0

# --- 아래 6개 패키지 추가 ---
  firebase_core: ^2.24.2
  firebase_messaging: ^14.7.9
  flutter_local_notifications: ^17.1.2
  dio: ^5.4.0                  # HTTP 통신 (JWT 처리용)
  flutter_secure_storage: ^9.0.0 # 기기 내 토큰 안전 보관용
  stomp_dart_client: ^3.0.1     # 실시간 채팅(웹소켓) 연결용

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
