name: open_source_software
description: "open_source_software"
version: 1.1.0

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  geolocator: ^14.0.2
  maps_toolkit: ^3.1.0
  dart_geohash: ^2.1.0

# --- 아래 6개 패키지 추가 ---
  firebase_core: ^4.0.0
  firebase_messaging: ^16.0.0
  flutter_local_notifications: ^17.1.2
  stomp_dart_client: ^3.0.1     # 실시간 채팅(웹소켓) 연결용
  flutter_secure_storage: ^10.3.0
  dio: ^5.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
